name: CICD

on:
  
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      - 
        name: Configure SSH
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
      - 
        name: Stop and remove Docker container
        run: |
          ssh -o StrictHostKeyChecking=no root@159.89.110.127 "docker stop digitalocean_web_1"
          ssh -o StrictHostKeyChecking=no root@159.89.110.127 "docker rm digitalocean_web_1"
      - 
        name: Start Docker container
        run: |
          ssh -o StrictHostKeyChecking=no root@159.89.110.127 "docker run --name digitalocean_web_1 -d carrion14/frontend:latest"
